import React from 'react';
import { Card } from '../components/Card';

export const Education: React.FC = () => {
  return (
    <div className="animate-fade-in" style={{ maxWidth: '900px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      <h2 style={{ textAlign: 'center', marginBottom: '1rem' }}>Education & Awareness</h2>
      <p style={{ textAlign: 'center', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
        Learn more about climate change and how small actions create massive global impact.
      </p>

      <Card>
        <h3 style={{ color: 'var(--accent-primary)', marginBottom: '1rem' }}>What is a Carbon Footprint?</h3>
        <p style={{ color: 'var(--text-secondary)', lineHeight: '1.8' }}>
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. 
          The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. 
          Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, 
          the average global carbon footprint per year needs to drop to under 2 tons by 2050.
        </p>
      </Card>

      <Card>
        <h3 style={{ color: 'var(--accent-primary)', marginBottom: '1rem' }}>Climate Change Basics</h3>
        <p style={{ color: 'var(--text-secondary)', lineHeight: '1.8' }}>
          Greenhouse gases trap heat in the atmosphere, leading to global warming. While some greenhouse gases occur naturally, 
          human activities—particularly the burning of fossil fuels (coal, oil, and natural gas) for energy, transportation, 
          and industrial processes—have significantly increased their concentration. This leads to rising sea levels, 
          extreme weather events, and disruption of ecosystems.
        </p>
      </Card>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '2rem' }}>
        <Card>
          <h3 style={{ color: 'var(--accent-primary)', marginBottom: '1rem' }}>Renewable Energy</h3>
          <p style={{ color: 'var(--text-secondary)' }}>
            Switching to renewable energy sources like solar, wind, and hydro power drastically reduces reliance on fossil fuels. 
            Even as a renter, you can often opt-in to clean energy programs through your local utility provider.
          </p>
        </Card>

        <Card>
          <h3 style={{ color: 'var(--accent-primary)', marginBottom: '1rem' }}>Recycling Benefits</h3>
          <p style={{ color: 'var(--text-secondary)' }}>
            Recycling reduces the need for extracting, refining, and processing raw materials all of which create substantial air and water pollution. 
            It saves energy and reduces greenhouse gas emissions, tackling climate change.
          </p>
        </Card>
      </div>

      <Card style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--accent-primary)' }}>
        <h3 style={{ marginBottom: '1rem' }}>Sustainable Living Tips</h3>
        <ul style={{ color: 'var(--text-secondary)', paddingLeft: '1.5rem', lineHeight: '1.8' }}>
          <li><strong>Reduce Meat Consumption:</strong> Livestock farming generates 14.5% of global greenhouse gas emissions.</li>
          <li><strong>Energy Efficiency:</strong> Replace old incandescent bulbs with LEDs to use 75% less energy.</li>
          <li><strong>Active Transport:</strong> Walk or bike for trips under 2 miles instead of driving.</li>
          <li><strong>Composting:</strong> Organic waste in landfills generates methane. Composting turns it into nutrient-rich soil.</li>
        </ul>
      </Card>
    </div>
  );
};
