import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/Button';
import { Card } from '../components/Card';

export const Home: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="animate-fade-in" style={{ 
      display: 'flex', 
      flexDirection: 'column', 
      justifyContent: 'center', 
      gap: '2rem',
      height: 'calc(100vh - 180px)', // Adjust for navbar and root padding
      overflow: 'hidden'
    }}>
      {/* Hero Section */}
      <section style={{ textAlign: 'center' }}>
        <h1 className="hero-title" style={{ fontSize: '4rem', marginBottom: '1rem', background: 'linear-gradient(to right, var(--accent-primary), var(--accent-secondary))', WebkitBackgroundClip: 'text', color: 'transparent' }}>
          EcoAssist
        </h1>
        <p className="hero-subtitle" style={{ fontSize: '1.5rem', color: 'var(--text-secondary)', marginBottom: '2rem' }}>
          A Smart Carbon Footprint Awareness Platform that <b>tracks your individual environmental impact</b> and offers <b>actionable insights for reducing your daily footprints</b>.
        </p>
        <Button onClick={() => navigate('/calculator')} style={{ fontSize: '1.2rem', padding: '0.8rem 2rem' }}>
          Start Now
        </Button>
      </section>

      {/* About / Why It Matters */}
      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '1rem', overflowY: 'auto', paddingRight: '0.5rem' }}>
        <Card style={{ padding: '1.5rem' }}>
          <h3 style={{ color: 'var(--accent-primary)', marginBottom: '0.5rem', fontSize: '1.1rem' }}>About Carbon Footprint</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            A carbon footprint is the total amount of greenhouse gases generated by our actions.
          </p>
        </Card>
        
        <Card style={{ padding: '1.5rem' }}>
          <h3 style={{ color: 'var(--accent-primary)', marginBottom: '0.5rem', fontSize: '1.1rem' }}>Why It Matters</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            High emissions lead to climate change. Understanding our footprint helps mitigate these effects.
          </p>
        </Card>
        
        <Card style={{ padding: '1.5rem' }}>
          <h3 style={{ color: 'var(--accent-primary)', marginBottom: '0.5rem', fontSize: '1.1rem' }}>How It Works</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
            1. Calculate<br/>
            2. Analyze Dashboard<br/>
            3. Act on Recommendations
          </p>
        </Card>
      </section>
    </div>
  );
};
